function [final_vote] = weighted_average(weights, Yhat, constrain)
% Given a collection of numeric classes, weights, and predictions, this function
% will generate a weighted averae
%
%   [weights] 1 x K; the relative assigned to each algorithm that generated 
%     the predictions in Yhat. The weight weights(i) corresponds to the 
%     predictions from the i-th algorithm that generated Yhat(i)
%
%   [Yhat] The N x K prediction matrix, where the i-th column specifies
%     the predictions generated by the i-th model
%
%   [constrain] 2 x 1 min / max values to constrain to
%
%   [final_vote] N x 1 vector containing the final, weighted vote
%
[~, K] = size(Yhat);

assert(numel(weights) == K);

avg = round(sum(bsxfun(@times, Yhat, weights), 2) ./ sum(weights));

minVal = constrain(1);
maxVal = constrain(2);

avg(avg >= maxVal) = maxVal;
avg(avg <= minVal) = minVal;

final_vote = avg;
