function [final_vote] = weighted_average(weights, Yhat)
% Given a collection of numeric classes, weights, and predictions, this function
% will generate a weighted averae
%
%   [weights] 1 x K; the relative assigned to each algorithm that generated 
%     the predictions in Yhat. The weight weights(i) corresponds to the 
%     predictions from the i-th algorithm that generated Yhat(i)
%
%   [Yhat] The N x K prediction matrix, where the i-th column specifies
%     the predictions generated by the i-th model
%
%   [final_vote] N x 1 vector containing the final, weighted vote
%
[~, K] = size(Yhat);

assert(numel(weights) == K);

final_vote = sum(bsxfun(@times, Yhat, weights), 2) ./ sum(weights);